# Generated by Django 6.0.2 on 2026-02-10 02:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor alvo')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Data alvo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ('-is_active', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='GoalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_entries', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='goals.savinggoal', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Lancamento do objetivo',
                'verbose_name_plural': 'Lancamentos do objetivo',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['user', 'date'], name='goals_goale_user_id_701db0_idx'), models.Index(fields=['goal', 'date'], name='goals_goale_goal_id_6a2765_idx')],
            },
        ),
    ]
