# Generated by Django 5.2.11 on 2026-03-24 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goalentry',
            name='goals_goale_user_id_701db0_idx',
        ),
        migrations.AddField(
            model_name='goalentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='goalentry',
            index=models.Index(fields=['tenant', 'date'], name='goals_goale_tenant__abbac8_idx'),
        ),
    ]
