# Generated by Django 6.0.2 on 2026-02-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Banco'), ('cash', 'Dinheiro'), ('card', 'Cartao')], default='bank', max_length=20, verbose_name='Tipo'),
        ),
    ]
