# Generated by Django 6.0.2 on 2026-03-23 00:00

from django.db import migrations, models


def disable_balance_for_existing_card_accounts(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(account_type="card").update(include_in_balance=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="include_in_balance",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Desmarque para contas que nao devem compor os saldos "
                    "consolidados, como cartao de credito."
                ),
                verbose_name="Considerar no saldo",
            ),
        ),
        migrations.RunPython(
            disable_balance_for_existing_card_accounts,
            migrations.RunPython.noop,
        ),
    ]
