# Generated by Django 6.0.2 on 2026-05-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_unique_account_name_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Banco'), ('cash', 'Dinheiro'), ('card', 'Cartão')], default='bank', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='include_in_balance',
            field=models.BooleanField(default=True, help_text='Desmarque para contas que nao devem compor os saldos consolidados, como cartão de crédito.', verbose_name='Considerar no saldo'),
        ),
    ]
