# Generated by Django 6.0.2 on 2026-02-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date', '-created_at'), 'verbose_name': 'Transacao', 'verbose_name_plural': 'Transacoes'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(default=1, help_text='Preparado para futura automacao de recorrencias.', verbose_name='Intervalo de recorrencia'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence_type',
            field=models.CharField(choices=[('fixed', 'Fixa'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='fixed', max_length=20, verbose_name='Recorrencia'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('transfer', 'Transferencia')], max_length=20, verbose_name='Tipo'),
        ),
    ]
