# Generated by Django 6.0.2 on 2026-02-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Informe apenas quando a recorrencia for Parcelado.', null=True, verbose_name='Quantidade de parcelas'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence_type',
            field=models.CharField(choices=[('fixed', 'Fixa'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('installment', 'Parcelado')], default='fixed', max_length=20, verbose_name='Recorrencia'),
        ),
    ]
