# Generated by Django 6.0.2 on 2026-02-10 02:46

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def set_initial_clearance(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")
    today = django.utils.timezone.localdate()
    Transaction.objects.filter(date__lte=today).update(is_cleared=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_account_type"),
        ("categories", "0001_initial"),
        ("transactions", "0003_transaction_installment_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_cleared",
            field=models.BooleanField(
                default=False,
                help_text="Marque quando a transacao ja foi recebida/paga.",
                verbose_name="Baixada",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "is_cleared", "date"],
                name="transaction_user_id_7ca50e_idx",
            ),
        ),
        migrations.RunPython(set_initial_clearance, noop_reverse),
    ]
