# Generated by Django 6.0.2 on 2026-02-10 03:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_is_cleared_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('is_closed', models.BooleanField(default=True, verbose_name='Fechado')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fechado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mes fechado',
                'verbose_name_plural': 'Meses fechados',
                'ordering': ('-year', '-month'),
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_closed_month_per_user')],
            },
        ),
    ]
