# Generated by Django 6.0.2 on 2026-02-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_closedmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurrence_interval_unit',
            field=models.CharField(choices=[('day', 'Dias'), ('month', 'Mes'), ('year', 'Ano')], default='month', max_length=10, verbose_name='Unidade do intervalo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numero do intervalo para gerar as proximas recorrencias.', verbose_name='Intervalo de recorrencia'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Unica'), ('fixed', 'Fixa'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('installment', 'Parcelado')], default='once', max_length=20, verbose_name='Recorrencia'),
        ),
    ]
