# Generated by Django 6.0.2 on 2026-02-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_recurrence_interval_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_ignored',
            field=models.BooleanField(default=False, help_text='Quando marcada, a despesa nao entra nos saldos e indicadores.', verbose_name='Ignorada'),
        ),
    ]
