# Generated by Django 6.0.2 on 2026-02-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_is_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Indice da parcela atual dentro do plano parcelado.', null=True, verbose_name='Numero da parcela'),
        ),
    ]
