# Generated by Django 5.2.11 on 2026-03-24 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_unique_account_name_per_user_and_more'),
        ('categories', '0002_remove_category_unique_category_name_type_per_user_and_more'),
        ('tenants', '0001_initial'),
        ('transactions', '0009_backfill_installment_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='closedmonth',
            name='unique_closed_month_per_user',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_8af7f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_98a6b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_7ca50e_idx',
        ),
        migrations.AddField(
            model_name='closedmonth',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_months', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'date'], name='transaction_tenant__ae6dce_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'transaction_type'], name='transaction_tenant__03565d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'is_cleared', 'date'], name='transaction_tenant__fe02b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='closedmonth',
            constraint=models.UniqueConstraint(fields=('tenant', 'year', 'month'), name='unique_closed_month_per_tenant'),
        ),
    ]
