# Generated by Django 5.2.11 on 2026-03-06 02:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Item')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preco unitario estimado')),
                ('notes', models.CharField(blank=True, max_length=220, verbose_name='Observacao')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Comprado')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Comprado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de compra',
                'verbose_name_plural': 'Itens de compra',
                'ordering': ('is_purchased', '-updated_at', '-created_at'),
                'indexes': [models.Index(fields=['user', 'is_purchased', 'updated_at'], name='shopping_sh_user_id_99154b_idx'), models.Index(fields=['user', 'created_at'], name='shopping_sh_user_id_a6a311_idx')],
            },
        ),
    ]
