# Generated by Django 6.0.2 on 2026-03-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_existing_items_to_default_lists(apps, schema_editor):
    ShoppingItem = apps.get_model("shopping", "ShoppingItem")
    ShoppingList = apps.get_model("shopping", "ShoppingList")

    user_ids = (
        ShoppingItem.objects.filter(shopping_list__isnull=True)
        .values_list("user_id", flat=True)
        .distinct()
    )

    for user_id in user_ids:
        shopping_list, _ = ShoppingList.objects.get_or_create(
            user_id=user_id,
            name="Lista principal",
            defaults={
                "notes": "Migrada automaticamente da lista antiga.",
            },
        )
        ShoppingItem.objects.filter(
            user_id=user_id,
            shopping_list__isnull=True,
        ).update(shopping_list=shopping_list)


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Lista")),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=220,
                        verbose_name="Observacao",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de compra",
                "verbose_name_plural": "Listas de compra",
                "ordering": ("-updated_at", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_shopping_list_name_per_user",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="shoppingitem",
            name="shopping_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shopping.shoppinglist",
                verbose_name="Lista",
            ),
        ),
        migrations.RunPython(
            move_existing_items_to_default_lists,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="shoppingitem",
            name="shopping_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shopping.shoppinglist",
                verbose_name="Lista",
            ),
        ),
        migrations.RemoveIndex(
            model_name="shoppingitem",
            name="shopping_sh_user_id_99154b_idx",
        ),
        migrations.AddIndex(
            model_name="shoppingitem",
            index=models.Index(
                fields=["user", "shopping_list", "is_purchased", "updated_at"],
                name="shop_item_user_list_idx",
            ),
        ),
    ]
