# Generated by Django 6.0.2 on 2026-03-23 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_shopping_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="list_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="Data da lista",
            ),
        ),
    ]
