# Generated by Django 5.2.11 on 2026-03-24 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_shoppinglist_list_date'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shopping_list_name_per_user',
        ),
        migrations.RemoveIndex(
            model_name='shoppingitem',
            name='shopping_sh_user_id_a6a311_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppingitem',
            name='shop_item_user_list_idx',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['tenant', 'shopping_list', 'is_purchased', 'updated_at'], name='shop_item_tenant_list_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['tenant', 'created_at'], name='shopping_sh_tenant_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_shopping_list_name_per_tenant'),
        ),
    ]
